### PR TITLE
Correct vendor files

### PR DESCRIPTION
**Pull request by pmckelvy1**

### CODE REVIEW

**Comment by tbrent** [comment]
Imports are broken elsewhere, but overall the change LGTM and we can merge after fixing

**Comment by akshatmittal** [comment]
Possible to maybe not merge this until we move to the monorepo? Or be the first thing to be merged before any other changes so I can move this over.

**Comment by tbrent** [comment]
> Possible to maybe not merge this until we move to the monorepo? Or be the first thing to be merged before any other changes so I can move this over.

The C4 coordinators already managed to count SLOC exempting these folders, but I think it's going to end up being important for the individual wardens during their audit that this code is cleanly separated out.

**Comment by akshatmittal** [comment]
Yeah, we've already merged other things so might as well merge this. I'll move things together.

**Pull request merged**
