### PR TITLE
ApxEth plugin and scripts

### PR DESCRIPTION
**Pull request by julianmrodri**
* ApxETH Plugin and tests

### CODE REVIEW

**Review by tbrent — APPROVED** [review]
LGTM!

**Comment by tbrent** [comment]
the question I maybe wanted to raise was whether we should consider a longer delay until default, such as 72 hrs

@pmckelvy1 @akshatmittal

**Comment by pmckelvy1** [comment]
> the question I maybe wanted to raise was whether we should consider a longer delay until default, such as 72 hrs
> 
> @pmckelvy1 @akshatmittal

what would be the reasoning?

**Review by pmckelvy1 — DISMISSED** [review]
lgtm

**Comment by pmckelvy1** [comment]
let's leave this open until it gets audited

**Review by tbrent — DISMISSED** [review]

**Review by tbrent — APPROVED** [review]

**Review by tbrent — APPROVED** [review]

**Pull request merged**
