### PR TITLE
USDe plugin and scripts

### PR DESCRIPTION
**Pull request by julianmrodri**
USDe plugin, tests, and deployment/verification scripts.

### CODE REVIEW

**Review by tbrent — DISMISSED** [review]
LGTM!

**Review by pmckelvy1 — DISMISSED** [review]
lgtm

**Comment by pmckelvy1** [comment]
noting that this plugin is intended to have a larger default threshold to give USDe more room to depeg and repeg, without forcing the RToken to sell at a loss.

**Comment by pmckelvy1** [comment]
leaving this pr open until it gets audited

**Review by tbrent — APPROVED** [review]

**Pull request merged**
