### PR TITLE
StakeDAO USDC/USDC+ plugin scripts

### PR DESCRIPTION
**Pull request by tbrent**
Revenue hiding amount to be confirmed by backtesting

### CODE REVIEW

**Review by julianmrodri — APPROVED** [review]
LGTM, so we dont need a wrapper in this case?

**Comment by tbrent** [comment]
> LGTM, so we dont need a wrapper in this case?

I don't believe so. I believe the Gauge token is everything we need: transferrable, earns rewards, non-rebasing

**Comment by tbrent** [comment]
> LGTM, so we dont need a wrapper in this case?

Don't believe so: believe the Gauge token is (i) transferrable, (ii) non-rebasing, and (iii) and earns rewards

**Review by akshatmittal — APPROVED** [review]
TBD: Testing on the forknet. Scripts look good!

**Pull request merged**
