### PR TITLE
Stargate fixes

### PR DESCRIPTION
**Pull request by pmckelvy1**

### CODE REVIEW

**Comment by akshatmittal** [comment]
I'd also recommend looking at the deployment parameters. We likely need to tighten them here.

**Comment by pmckelvy1** [comment]
> I'd also recommend looking at the deployment parameters. We likely need to tighten them here.

what do you think we should tighten?

**Comment by akshatmittal** [comment]
> what do you think we should tighten?

Have a look at the peg parameters and error settings.

**Comment by akshatmittal** [comment]
lgtm

**Pull request merged**
