### PR TITLE
Disable dutch auctions per-collateral

### PR DESCRIPTION
**Pull request by tbrent**
https://github.com/code-423n4/2023-06-reserve-findings/issues/47 mitigation.

Switches to a 4-piecewise design. 

Over the first 20% there's a geometric decay from 1000x to 1.5x where the price falls by ~20% each block. If the auction clears in this window, a violation is reported and the dutch auction is disabled for both the tokens in the pair. 

Over the next 25% of the auction there's a linear decay from 1.5x to 1x, and price falls about ~0.8% per block. If the auction clears in this window, no violation is reported.

Over the next 50% of the auction there's a linear decay from the best price to the floor price, and price falls about ~0.065% per block. This is where we expect auctions to clear typically.

In the last 5% of the auction the price is constant at the floor price. 

The idea is the first section is for detecting when prices are being manipulated; the second section is for handling volatile tokens like RSR that may change price up to 50% after the auction is started; and the third section is the typical case. We have the 4th section for when no bots are integrated yet and a human is trying to do the bidding. 

```
======== Phase 1 =========
BigNumber { value: "10202021020953691201530" }
BigNumber { value: "8214022309800292628930" }
BigNumber { value: "6613411437530028669480" }
BigNumber { value: "5324700760779452177520" }
BigNumber { value: "4287112401770412068800" }
BigNumber { value: "3451715307673806653830" }
BigNumber { value: "2779102933240321900730" }
BigNumber { value: "2237557974834823439140" }
BigNumber { value: "1801540213161282812890" }
BigNumber { value: "1450486278406612873710" }
BigNumber { value: "1167839845303255313600" }
BigNumber { value: "940270807508876725420" }
BigNumber { value: "757046606184101099390" }
BigNumber { value: "609526063510649708290" }
BigNumber { value: "490751849442200159180" }
BigNumber { value: "395122756820964911360" }
BigNumber { value: "318127862407972769710" }
BigNumber { value: "256136441379719017220" }
BigNumber { value: "206224868535821945640" }
BigNumber { value: "166039225709272633380" }
BigNumber { value: "133684286816970141520" }
BigNumber { value: "107634135641261815490" }
BigNumber { value: "86660200918773283820" }
BigNumber { value: "69773314743869975840" }
BigNumber { value: "56177061658444821880" }
BigNumber { value: "45230263518752867180" }
BigNumber { value: "36416548530739276560" }
BigNumber { value: "29320302463898960510" }
BigNumber { value: "23606853786510323730" }
BigNumber { value: "19006746140625257910" }
BigNumber { value: "15303030303030303050" }
======== Phase 2 =========
BigNumber { value: "15167003367003367040" }
BigNumber { value: "15030976430976431010" }
BigNumber { value: "14894949494949494970" }
BigNumber { value: "14758922558922558960" }
BigNumber { value: "14622895622895622930" }
BigNumber { value: "14486868686868686890" }
BigNumber { value: "14350841750841750880" }
BigNumber { value: "14214814814814814840" }
BigNumber { value: "14078787878787878810" }
BigNumber { value: "13942760942760942800" }
BigNumber { value: "13806734006734006760" }
BigNumber { value: "13670707070707070730" }
BigNumber { value: "13534680134680134720" }
BigNumber { value: "13398653198653198680" }
BigNumber { value: "13262626262626262650" }
BigNumber { value: "13126599326599326630" }
BigNumber { value: "12990572390572390600" }
BigNumber { value: "12854545454545454570" }
BigNumber { value: "12718518518518518550" }
BigNumber { value: "12582491582491582520" }
BigNumber { value: "12446464646464646480" }
BigNumber { value: "12310437710437710470" }
BigNumber { value: "12174410774410774440" }
BigNumber { value: "12038383838383838400" }
BigNumber { value: "11902356902356902390" }
BigNumber { value: "11766329966329966350" }
BigNumber { value: "11630303030303030320" }
BigNumber { value: "11494276094276094310" }
BigNumber { value: "11358249158249158270" }
BigNumber { value: "11222222222222222240" }
BigNumber { value: "11086195286195286230" }
BigNumber { value: "10950168350168350190" }
BigNumber { value: "10814141414141414160" }
BigNumber { value: "10678114478114478140" }
BigNumber { value: "10542087542087542110" }
BigNumber { value: "10406060606060606080" }
BigNumber { value: "10270033670033670060" }
BigNumber { value: "10198699809907130130" }
======== Phase 3 =========
BigNumber { value: "10192059025680986310" }
BigNumber { value: "10185418241454842500" }
BigNumber { value: "10178777457228698680" }
BigNumber { value: "10172136673002554860" }
BigNumber { value: "10165495888776411050" }
BigNumber { value: "10158855104550267230" }
BigNumber { value: "10152214320324123410" }
BigNumber { value: "10145573536097979600" }
BigNumber { value: "10138932751871835780" }
BigNumber { value: "10132291967645691970" }
BigNumber { value: "10125651183419548150" }
BigNumber { value: "10119010399193404340" }
BigNumber { value: "10112369614967260520" }
BigNumber { value: "10105728830741116700" }
BigNumber { value: "10099088046514972890" }
BigNumber { value: "10092447262288829070" }
BigNumber { value: "10085806478062685260" }
BigNumber { value: "10079165693836541440" }
BigNumber { value: "10072524909610397620" }
BigNumber { value: "10065884125384253810" }
BigNumber { value: "10059243341158109990" }
BigNumber { value: "10052602556931966170" }
BigNumber { value: "10045961772705822360" }
BigNumber { value: "10039320988479678540" }
BigNumber { value: "10032680204253534730" }
BigNumber { value: "10026039420027390910" }
BigNumber { value: "10019398635801247100" }
BigNumber { value: "10012757851575103280" }
BigNumber { value: "10006117067348959460" }
BigNumber { value: "9999476283122815650" }
BigNumber { value: "9992835498896671830" }
BigNumber { value: "9986194714670528020" }
BigNumber { value: "9979553930444384200" }
BigNumber { value: "9972913146218240380" }
BigNumber { value: "9966272361992096570" }
BigNumber { value: "9959631577765952750" }
BigNumber { value: "9952990793539808930" }
BigNumber { value: "9946350009313665120" }
BigNumber { value: "9939709225087521300" }
BigNumber { value: "9933068440861377490" }
BigNumber { value: "9926427656635233670" }
BigNumber { value: "9919786872409089860" }
BigNumber { value: "9913146088182946040" }
BigNumber { value: "9906505303956802220" }
BigNumber { value: "9899864519730658410" }
BigNumber { value: "9893223735504514590" }
BigNumber { value: "9886582951278370780" }
BigNumber { value: "9879942167052226960" }
BigNumber { value: "9873301382826083140" }
BigNumber { value: "9866660598599939330" }
BigNumber { value: "9860019814373795510" }
BigNumber { value: "9853379030147651690" }
BigNumber { value: "9846738245921507880" }
BigNumber { value: "9840097461695364060" }
BigNumber { value: "9833456677469220250" }
BigNumber { value: "9826815893243076430" }
BigNumber { value: "9820175109016932620" }
BigNumber { value: "9813534324790788800" }
BigNumber { value: "9806893540564644980" }
BigNumber { value: "9800252756338501170" }
BigNumber { value: "9793611972112357350" }
BigNumber { value: "9786971187886213540" }
BigNumber { value: "9780330403660069720" }
BigNumber { value: "9773689619433925900" }
BigNumber { value: "9767048835207782090" }
BigNumber { value: "9760408050981638270" }
BigNumber { value: "9753767266755494450" }
BigNumber { value: "9747126482529350640" }
BigNumber { value: "9740485698303206820" }
BigNumber { value: "9733844914077063010" }
BigNumber { value: "9727204129850919190" }
BigNumber { value: "9720563345624775380" }
BigNumber { value: "9713922561398631560" }
BigNumber { value: "9707281777172487740" }
BigNumber { value: "9703961385059415830" }
======== Phase  4 =========
BigNumber { value: "9703961385059415830" }
BigNumber { value: "9703961385059415830" }
BigNumber { value: "9703961385059415830" }
BigNumber { value: "9703961385059415830" }
BigNumber { value: "9703961385059415830" }
BigNumber { value: "9703961385059415830" }
```

Something else I also threw in this PR (minor) is a switch of the minimum auction length from 2 blocks to 20 blocks, since the 4th phase of the auction wouldn't happen under 20 blocks.

### CODE REVIEW

**Comment by tbrent** [comment]
GIthub is having that weird bug again, closing PR and opening a new one

Screenshot 2023-07-27 at 10 20 22 PM

**Comment by tbrent** [comment]
Should be green after this run, ready for review. @akshatmittal you may need to handle this one since @pmckelvy1 is out

**Comment by akshatmittal** [comment]
The code itself looks good, just added some extra documentation, I do have a few thoughts:

1. Do we want to consider changing the 1.2x number? I don't have a good reasoning here, and maybe we don't even need to think too much about it but I can see a >1.2x change in prices within minutes in hyper volatile markets, the same situation where we expect a collateral to default.
2. We're doing a double conversion from blocks to time then back to blocks. This can open up the trade to time manipulation attacks. Just something to consider, we can possibly just use blocks for the entire operation here. (The last `worstPrice` tick will basically never happen for the same reason)

And just to recap the assumption, we're assuming that MEV is always honest and neutral towards the protocol in order for this system to make sense. Just recapping, no action to take here.

**Comment by tbrent** [comment]
I've implemented the changes we discussed. The only thing different is the 1.2x number I moved to 1.5x instead of 2x. We had the directionality of the RSR price change wrong: the case where RSR is changing drastically in price after a default is selling RSR for collateral, so RSR would need to _appreciate_ 51% after the auction was started in order to get into the geometric phase. Depreciation would just mean the auction doesn't clear.

**Comment by pmckelvy1** [comment]
imo 1.5x seems unnecessary and 1.2x is more than enough. a 20% price swing in 3 minutes is *a lot*

**Review by pmckelvy1 — CHANGES_REQUESTED** [review]

**Comment by pmckelvy1** [comment]
overall lgtm, just 2 comments that need fixing. nothing has come to mind as an issue for block vs timestamp use across the protocol but lets give it 1 more day to marinate

**Pull request merged**
