### PR TITLE
Single price

### PR DESCRIPTION
**Pull request by tbrent**

### CODE REVIEW

**Comment by tbrent** [comment]
@pmckelvy1 believe you already took a look, but I want you to be the one to hit the merge button

**Comment by tbrent** [comment]
Somehow the gas costs for rebalancing went up?

**Comment by tbrent** [comment]
there we go, just needed to get the right baselines. gas costs went down for rebalancing as expected, just by a lot less than I thought they would

**Review by pmckelvy1 — COMMENTED** [review]
lgtm

**Pull request merged**
