### PR TITLE
refactor: pipeline

### PR DESCRIPTION
**Pull request by DSergiu**
* updates actions to latest versions
* fixes caching of yarn packages (never seemed to work [ex1](https://github.com/reserve-protocol/protocol/runs/6818511861?check_suite_focus=true#step:5:8), [ex2](https://github.com/reserve-protocol/protocol/runs/6903347233?check_suite_focus=true#step:5:8))
  * should speed up the pipeline quite a bit
*  fixes caching of hardhat network fork
* replaces deprecated yarn arg `--frozen-lockfile` with suggested one `immutable`
* ignores IntelliJ `.idea` dir

### CODE REVIEW

**Comment by DSergiu** [comment]
Hey @julianmrodri . Would you retry the [pipeline](https://github.com/reserve-protocol/protocol/actions/runs/2511818390)? I am not sure why the integration test fail. Seems to be an [JSON-RPC error](https://github.com/reserve-protocol/protocol/runs/6916707257?check_suite_focus=true#step:7:94). Please take a look.

**Comment by DSergiu** [comment]
The [integration tests fail with](https://github.com/reserve-protocol/protocol/runs/6936148264?check_suite_focus=true#step:7:77):

```
2) Aave/Compound - Integration - Mainnet Forking P1
       Basket/Issue/Redeem
         "before all" hook for "Should register ERC20s and Assets/Collateral correctly":
     HardhatError: HH110: Invalid JSON-RPC response received: {"message":"Not Found","logref":null,"path":null,"_links":{"self":{"href":"/v2/","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Page Not Found","logref":null,"path":null,"_links":{},"_embedded":{}}]}}
      at parseJsonResponse (node_modules/hardhat/src/internal/util/jsonrpc.ts:47:11)
      at HttpProvider._fetchJsonRpcResponse (node_modules/hardhat/src/internal/core/providers/http.ts:206:31)
```

I don't see it being related to these changes. Any clues on this @tbrent ?

**Comment by tbrent** [comment]
Hi @DSergiu 

I'm not sure why it failed again. Will you open a new PR with these changes? I think we are interested in taking them, we just want to make sure it's passing CI.

**Comment by DSergiu** [comment]
> Hi @DSergiu
> 
> I'm not sure why it failed again. Will you open a new PR with these changes? I think we are interested in taking them, we just want to make sure it's passing CI.

Sure. Let me close this.

**Pull request closed without merging**
